name: Build Virtio GPU Drivers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Visual Studio 2022
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Download prebuilt Mesa binaries
      shell: powershell
      run: |
        curl https://github.com/YWFhYmJi/virtio-win-mesa/releases/download/akre-mesa-25.3.6-mingw-0403/mesa_x64_wow64.7z -O mesa_x64_wow64.7z
        curl https://github.com/YWFhYmJi/virtio-win-mesa/releases/download/akre-mesa-25.3.6-mingw-0403/vulkan_lvp_x64_wow64.7z -O vulkan_lvp_x64_wow64.7z
        7z x -o"$PWD\mesa_prebuilt" mesa_x64_wow64.7z
        7z x -o"$PWD\mesa_prebuilt" vulkan_lvp_x64_wow64.7z

    - name: Build drivers
      shell: powershell
      run: |
        $env:MESA_PREFIX = "$PWD\mesa_prebuilt\mesa_prefix"
        $env:MESA_PREFIX_WOW64 = "$PWD\mesa_prebuilt\mesa_prefix_wow64"
        $env:VIRTIO_WIN_NO_ARM = "1"
        cd viogpu
        .\build_AllNoSdv.bat

    - name: Upload artifact (x64)
      uses: actions/upload-artifact@v4
      with:
        name: viogpu_x64_build
        path: viogpu\Install\Win10\amd64

    - name: Upload artifact (x86)
      uses: actions/upload-artifact@v4
      with:
        name: viogpu_x86_build
        path: viogpu\Install\Win10\x86
